name: Ravi Teja Parishapogu
description: Product Engineer, Invana Tech Solutions
meta_description: "Product Engineer, Invana Tech Solutions"

#markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://iamravi.xyz'
#google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'RaviTeja'
